### PR TITLE
fix(lodash): Remove dependency on lodash

### LINKED ISSUE #128: Remove lodash dependency
Lodash is no longer a supported library. (no new releases since 2016)

Some of these might be replaceable with built-in APIs depending on the browser support target. For example lodash/cloneDeep could be replaced with [structuredClone()](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone).

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
## What
Closes #128 

## Description
Removes dependency on lodash

## Type of change
- [x] Refactoring (no functional changes, no api changes)

/cc @christianvogt

### CODE REVIEW

File: packages/module/src/elements/BaseElement.ts [hunk 1]
```diff
@@ -60,7 +59,7 @@ export default abstract class BaseElement<E extends ElementModel = ElementModel,
       controller: observable.ref,
       label: observable,
       style: observable,
-      ordering: computed({ equals: _.isEqual })
+      ordering: computed({ equals: (a, b) => JSON.stringify(a || {}) === JSON.stringify(b || {}) })
```
Comment (christianvogt) [inline packages/module/src/elements/BaseElement.ts:62]: This one concerns me a bit.
`ordering` is an array of numbers. Can we make a specific comparison function.

File: packages/module/src/layouts/BaseLayout.ts [hunk 2]
```diff
@@ -253,9 +252,9 @@ export class BaseLayout implements Layout {
       return undefined;
     }
 
-    let layoutNode = _.find(nodes, { id: node.getId() });
-    if (!layoutNode && _.size(node.getNodes())) {
-      layoutNode = _.find(nodes, { id: node.getChildren()[0].getId() });
+    let layoutNode = nodes.find(n =>  n.id === node.getId());
+    if (!layoutNode && node.getNodes().length) {
+      layoutNode = nodes.find(n => n.id === node.getChildren()[0].getId());
```
Comment (christianvogt) [inline packages/module/src/layouts/BaseLayout.ts:257]: IIRC for mobx performance, you'll want to cache the id instead of traversing the observables.
```suggestion
      const id = node.getChildren()[0].getId();
      layoutNode = nodes.find(n => n.id === id);
```

File: packages/module/src/layouts/DagreLayout.ts [hunk 3]
```diff
@@ -42,7 +41,7 @@ export class DagreLayout extends BaseLayout implements Layout {
   }
 
   protected updateEdgeBendpoints(edges: DagreLink[]): void {
-    _.forEach(edges, edge => {
+    edges?.forEach(edge => {
```
Comment (christianvogt) [inline packages/module/src/layouts/DagreLayout.ts:44]: Can this be
```suggestion
    edges.forEach(edge => {
```

File: packages/module/src/layouts/DagreLayout.ts [hunk 4]
```diff
@@ -55,26 +54,26 @@ export class DagreLayout extends BaseLayout implements Layout {
...
     if (initialRun || addingNodes) {
       const dagreGraph = new dagre.graphlib.Graph({ compound: true });
-      dagreGraph.setGraph(_.omit(this.dagreOptions, Object.keys(LAYOUT_DEFAULTS)));
+      const options = { ...this.dagreOptions };
+      Object.keys(LAYOUT_DEFAULTS).forEach(key => delete options[key]);
+      dagreGraph.setGraph(options);
 
       if (!this.dagreOptions.ignoreGroups) {
-        _.forEach(this.groups, group => {
+        this.groups?.forEach(group => {
```
Comment (christianvogt) [inline packages/module/src/layouts/DagreLayout.ts:62]: Can this be:
```suggestion
        this.groups.forEach(group => {
```

File: packages/module/src/utils/createAggregateEdges.ts [hunk 5]
```diff
@@ -88,7 +86,7 @@ const createAggregateEdges = (
       return newEdges;
     },
     [] as EdgeModel[]
-  );
+  ) ?? [];
```
Comment (christianvogt) [inline packages/module/src/utils/createAggregateEdges.ts:89]: I don't think it's possible for the return value to be `undefined` here.

File: packages/module/src/utils/element-utils.ts [hunk 6]
```diff
@@ -1,12 +1,11 @@
-import * as _ from 'lodash';
 import { GraphElement, Node, isNode, isGraph, NodeStyle } from '../types';
 
 const groupNodeElements = (nodes: GraphElement[]): Node[] => {
-  if (!_.size(nodes)) {
+  if (!nodes?.length) {
```
Comment (christianvogt) [inline packages/module/src/utils/element-utils.ts:4]: Can this be:
```suggestion
  if (!nodes.length) {
```

File: packages/module/src/utils/element-utils.ts [hunk 7]
```diff
@@ -23,23 +22,16 @@ const leafNodeElements = (nodeElements: Node | Node[] | null): Node[] => {
...
-    const children: GraphElement[] = nodeElements.getChildren();
-    if (_.size(children)) {
-      _.forEach(
-        children.filter(e => isNode(e)),
-        element => {
-          leafNodes.push(...leafNodeElements(element as Node));
-        }
-      );
-    }
+    const children: GraphElement[] = nodeElements.getChildren()?.filter(e => isNode(e));
```
Comment (christianvogt) [inline packages/module/src/utils/element-utils.ts:33]: I don't think children can be `undefined` here.

**Review by nicolethoen — APPROVED** [review]
LGTM

**Review by jenny-s51 — APPROVED** [review]
