### PR TITLE
fix(ContextSubMenuItem): fix popper container

### LINKED ISSUE #270: Bug - ContextSubMenuItem - Dropdown menu not being displayed correctly
**Describe the problem**
A clear and concise description of the problem. Which components are affected?

**How do you reproduce the problem?**
Provide steps to reproduce. A [codesandbox](https://codesandbox.io/s/serverless-cherry-q9t3f ) demonstrating the problem is appreciated.

Nest a `ContextSubMenuItem` inside of a `ContextMenu`:

```jsx
export const UncontrolledContextMenu = () => (
  <>
    <p>Dismiss the context menu by pressing `ESC` or clicking away.</p>
    <ContextMenu reference={{ x: 350, y: 250 }}>
      <ContextSubMenuItem label="parent">
        <DropdownItem label="a">a</DropdownItem>
        <DropdownItem label="a">b</DropdownItem>
      </ContextSubMenuItem>
    </ContextMenu>
  </>
);
```

**Expected behavior**
A clear and concise description of the expected behavior.

The `ContextSubMenuItem` dropdown menu shows up next to the already open one

**Is this issue blocking you?**
List the workaround if there is one.

yes. no workaround found just yet

**Screenshots**
If applicable, add screenshots to help explain the issue.

Image

https://github.com/user-attachments/assets/b72bddc2-35f4-4cad-9bb9-59207ad93952

**What is your environment?**

Fedora 41, Firefox 134.0.2

**What is your product and what release date are you targeting?**
OCP Console 4.19

**Any other information?**
The ContainerNode for the popper is not being set correctly, so it defaults to document.body, which probably explains this bug

### PR DESCRIPTION
**Pull request by logonoff**
## What
Closes #270 

## Description

The root issue ended up being that `Dropdown` also implements a `Popper`, so although the topology portal goes to the correct element in the DOM, the portal inside the Dropdown goes to `document.body`. Since the Dropdown is a child of the topology popper, it takes precedence, causing the children to go to the body instead of its intended location

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review

https://github.com/user-attachments/assets/ddce12d2-4c2f-48cc-85a2-6874a8c8ea3c

### CODE REVIEW

File: packages/module/src/components/contextmenu/ContextSubMenuItem.tsx [hunk 1]
```diff
@@ -77,11 +81,12 @@ const ContextSubMenuItem: React.FunctionComponent<ContextSubMenuItemProps> = ({
               e.stopPropagation();
             }
           }}
+          ref={subMenuRef}
+          role="presentation"
+          isNavFlyout
         >
-          <Dropdown toggle={() => <></>} className={css(topologyStyles.topologyContextMenuCDropdownMenu)}>
```
Comment (kmcfaul) [inline packages/module/src/components/contextmenu/ContextSubMenuItem.tsx:81]: Is this class still needed?

Comment (logonoff) [reply packages/module/src/components/contextmenu/ContextSubMenuItem.tsx:81]: It's also used here:

https://github.com/patternfly/react-topology/blob/dc28e8bf77e363eda3507a6b547ecafaa916a611/packages/module/src/components/contextmenu/ContextMenu.tsx#L33

File: packages/module/src/components/contextmenu/ContextSubMenuItem.tsx [hunk 2]
```diff
@@ -11,6 +11,11 @@ interface ContextSubMenuItemProps {
   children: React.ReactNode[];
 }
 
+/** Check if an event target is also a node. Needed to stop runtime errors where the target does not implement Node. */
+const isNode = (node: any): boolean => {
```
Comment (jeff-phillips-18) [inline packages/module/src/components/contextmenu/ContextSubMenuItem.tsx:15]: Can we rename this to `isHTMLNode` or something not to be confused with a Topology `Node`?

Comment (logonoff) [reply packages/module/src/components/contextmenu/ContextSubMenuItem.tsx]: Sure! I renamed it to `implementsDOMNode`

**Review by jeff-phillips-18 — APPROVED** [review]

**Review by kmcfaul — APPROVED** [review]
