### PR TITLE
fix(types): Work around to fix issue with consumers recieving a type error.

### LINKED ISSUE #165: Error with 5.3.0-prerelease.5 running Patternfly release candidate 5.3
**Describe the problem**
Openshift is seeing the following error when running verison **@patternfly/react-topology": "5.3.0-prerelease.5** of react topology.

`
ERROR in node_modules/@patternfly/react-topology/src/components/layers/Layer.tsx:76:24
TS2322: Type '{ children: ReactNode; ref: MutableRefObject<SVGGElement>; }' is not assignable to type 'IntrinsicAttributes & RefAttributes<unknown>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & RefAttributes<unknown>'.
    74 |   }, [order, layerNode]);
    75 |
  > 76 |   return createPortal(<LayerContainer ref={nodeRef}>{children}</LayerContainer>, layerNode);
       |                        ^^^^^^^^^^^^^^
    77 | });
    78 |
    79 | const Layer: React.FunctionComponent<LayerProps> = ({ id, children, orderKey }) =>

ERROR in node_modules/@patternfly/react-topology/src/components/layers/LayerContainer.tsx:11:29
TS2694: Namespace 'React' has no exported member 'ForwardRefRenderFunction'.
     9 | }
    10 |
  > 11 | const LayerContainer: React.ForwardRefRenderFunction<SVGGElement, LayerContainerProps> = ({ children }, ref) => {
       |                             ^^^^^^^^^^^^^^^^^^^^^^^^
    12 |   // accumulate parent positions
    13 |   const element = React.useContext(ElementContext);
    14 |   let p = element;

ERROR in node_modules/@patternfly/react-topology/src/components/popper/Popper.tsx:199:51
TS2724: 'React' has no exported member named 'RefCallback'. Did you mean 'useCallback'?
    197 |   ]);
    198 |
  > 199 |   const nodeRefCallback = React.useCallback<React.RefCallback<HTMLDivElement>>(
        |                                                   ^^^^^^^^^^^
    200 |     node => {
    201 |       nodeRef.current = node;
    202 |       initialize();

ERROR in node_modules/@patternfly/react-topology/src/layouts/BreadthFirstLayout.ts:13:11
TS6133: 'gridOptions' is declared but its value is never read.
    11 |
    12 | export class BreadthFirstLayout extends BaseLayout implements Layout {
  > 13 |   private gridOptions: BreadthFirstLayoutOptions;
       |           ^^^^^^^^^^^
    14 |
    15 |   constructor(graph: Graph, options?: Partial<BreadthFirstLayoutOptions>) {
    16 |     super(graph, options);

ERROR in node_modules/@patternfly/react-topology/src/layouts/GridLayout.ts:13:11
TS6133: 'gridOptions' is declared but its value is never read.
    11 |
    12 | export class GridLayout extends BaseLayout implements Layout {
  > 13 |   private gridOptions: GridLayoutOptions;
       |           ^^^^^^^^^^^
    14 |
    15 |   constructor(graph: Graph, options?: Partial<GridLayoutOptions>) {`

** Additional Information **

The following are the release candidate versions:

"@patternfly/patternfly": "5.3.0-prerelease.5",
"@patternfly/react-charts": "7.3.0-prerelease.6",
"@patternfly/react-code-editor": "5.3.0-prerelease.25",
"@patternfly/react-core": "5.3.0-prerelease.23",
"@patternfly/react-drag-drop": "5.3.0-prerelease.23",
"@patternfly/react-icons": "5.3.0-prerelease.3",
"@patternfly/react-styles": "5.3.0-prerelease.3",
"@patternfly/react-table": "5.3.0-prerelease.25",
"@patternfly/react-templates": "1.0.0-prerelease.6",
"@patternfly/react-tokens": "5.3.0-prerelease.3",
"@patternfly/react-topology": "5.3.0-prerelease.5",
"@patternfly/quickstarts": "5.3.0-prerelease.1"

**What is your product and what release date are you targeting?**
This is for release of 5.3.0 of PatternFly.

### PR DESCRIPTION
**Pull request by dlabaj**
## What
Closes #165 

## Description
Fixes issue where consumers are receiving a type error  when using an older version for react-types.

### CODE REVIEW

**Comment by jschuler** [comment]
LGTM, not necessary, but to take it a step further you could also change as @wise-king-sullyman pointed out in slack:
> Looks like there’s a few other places where it’s importing from that barrel file as well (BaseGraph.ts, TaskEdge.tsx, TaskNode.tsx, WhenDecorator.tsx)

**Review by jschuler — APPROVED** [review]

**Review by jenny-s51 — APPROVED** [review]
LGTM 👍

We'll have to look into why the PR preview is erroring out... Opened an issue to track it [here](https://github.com/patternfly/react-topology/issues/175)

File: packages/module/src/types.ts [hunk 1]
```diff
@@ -3,7 +3,7 @@ import Point from './geom/Point';
 import Dimensions from './geom/Dimensions';
 import Rect from './geom/Rect';
 import { Padding, Translatable } from './geom/types';
-import { LayoutOptions } from './layouts';
+import { LayoutOptions } from './layouts/LayoutOptions';
```
Comment (jeff-phillips-18) [inline packages/module/src/types.ts:6]: Yes, `types` should never include a full directory only the direct dependents.

**Review by jeff-phillips-18 — APPROVED** [review]
